#!/bin/bash

# Sterling Setup Script for hdresearch/chelsea -> SDK + vers-docs Automation
# This script sets up Sterling to automatically generate SDKs and documentation
# when OpenAPI specs change in hdresearch/chelsea

set -e

echo "🚀 Setting up Sterling for hdresearch/chelsea automation..."

# Check prerequisites
echo "📋 Checking prerequisites..."

if ! command -v zig &> /dev/null; then
    echo "❌ Zig is required but not installed. Please install Zig 0.15.2+"
    exit 1
fi

if ! command -v git &> /dev/null; then
    echo "❌ Git is required but not installed."
    exit 1
fi

echo "✅ Prerequisites check passed"

# Build Sterling
echo "🔨 Building Sterling..."
zig build -Doptimize=ReleaseFast

if [ ! -f "./zig-out/bin/sterling" ]; then
    echo "❌ Sterling build failed"
    exit 1
fi

echo "✅ Sterling built successfully"

# Set up environment variables
echo "🔧 Setting up environment variables..."

cat > .env << 'ENVEOF'
# Required for LLM enhancement
ANTHROPIC_API_KEY=your_anthropic_api_key_here

# Required for GitHub automation
GITHUB_TOKEN=your_github_personal_access_token_here

# Required for webhook security
WEBHOOK_SECRET=your_webhook_secret_here

# Optional: Package publishing tokens
NPM_TOKEN=your_npm_token_here
PYPI_TOKEN=your_pypi_token_here

# Optional: Slack notifications
SLACK_WEBHOOK_URL=your_slack_webhook_url_here
ENVEOF

echo "✅ Created .env file - please edit with your actual tokens"

# Copy the Chelsea configuration
cp sterling-chelsea-config.toml sterling.toml

echo "✅ Created sterling.toml configuration for Chelsea"

# Create webhook server script
cat > webhook-server.sh << 'SERVEREOF'
#!/bin/bash

# Simple webhook server using Sterling
# This would be enhanced to include actual HTTP server functionality

echo "🌐 Starting Sterling webhook server..."
echo "Listening for GitHub webhooks from hdresearch/chelsea..."
echo "When OpenAPI changes are detected, Sterling will:"
echo "  1. Generate SDKs for TypeScript, Rust, Python, Go"
echo "  2. Enhance code with LLM"
echo "  3. Create/update GitHub repositories"
echo "  4. Generate documentation for vers-docs"
echo "  5. Create pull requests"

# In a real implementation, this would start an HTTP server
# For now, we'll show how to manually trigger the pipeline

echo ""
echo "To manually trigger SDK generation:"
echo "./zig-out/bin/sterling generate --spec path/to/openapi.yaml --config sterling.toml --enhance"
SERVEREOF

chmod +x webhook-server.sh

# Create documentation sync script
cat > sync-vers-docs.sh << 'SYNCEOF'
#!/bin/bash

# Script to sync generated documentation with hdresearch/vers-docs

set -e

echo "📚 Syncing documentation with hdresearch/vers-docs..."

# Check if docs were generated
if [ ! -d "./generated/docs" ]; then
    echo "❌ No generated docs found. Run Sterling generate first."
    exit 1
fi

# Clone or update vers-docs repository
if [ ! -d "./vers-docs" ]; then
    echo "📥 Cloning hdresearch/vers-docs..."
    git clone https://github.com/hdresearch/vers-docs.git
else
    echo "🔄 Updating vers-docs..."
    cd vers-docs
    git pull origin main
    cd ..
fi

# Copy generated docs to vers-docs
echo "📋 Copying generated documentation..."
mkdir -p vers-docs/docs/chelsea
cp -r generated/docs/* vers-docs/docs/chelsea/

# Create pull request (requires gh CLI)
cd vers-docs

if command -v gh &> /dev/null; then
    echo "🔀 Creating pull request..."
    
    # Create a new branch
    BRANCH_NAME="chelsea-docs-update-$(date +%Y%m%d-%H%M%S)"
    git checkout -b "$BRANCH_NAME"
    
    # Add and commit changes
    git add docs/chelsea/
    git commit -m "Update Chelsea API documentation

- Auto-generated from OpenAPI specification
- Updated SDK documentation for all languages
- Generated by Sterling SDK Generator"
    
    # Push and create PR
    git push origin "$BRANCH_NAME"
    gh pr create \
        --title "Update Chelsea API Documentation" \
        --body "Automated documentation update from Sterling SDK Generator.

This PR includes:
- Updated API reference documentation
- SDK installation and usage guides
- Code examples for all supported languages

Generated from the latest OpenAPI specification in hdresearch/chelsea." \
        --base main \
        --head "$BRANCH_NAME"
    
    echo "✅ Pull request created successfully"
else
    echo "⚠️  GitHub CLI not found. Please manually create a pull request with the changes."
    echo "   Branch: $BRANCH_NAME"
fi

cd ..
SYNCEOF

chmod +x sync-vers-docs.sh

# Create automation workflow example
mkdir -p .github/workflows

cat > .github/workflows/sterling-automation.yml << 'WORKFLOWEOF'
name: Sterling SDK Generation

on:
  repository_dispatch:
    types: [openapi-updated]
  workflow_dispatch:
    inputs:
      openapi_url:
        description: 'URL to OpenAPI specification'
        required: true
        default: 'https://raw.githubusercontent.com/hdresearch/chelsea/main/openapi.yaml'

jobs:
  generate-sdks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Sterling
      uses: actions/checkout@v4
      
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.15.2
        
    - name: Build Sterling
      run: zig build -Doptimize=ReleaseFast
      
    - name: Download OpenAPI Spec
      run: |
        curl -o openapi.yaml "${{ github.event.inputs.openapi_url || 'https://raw.githubusercontent.com/hdresearch/chelsea/main/openapi.yaml' }}"
        
    - name: Generate SDKs
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./zig-out/bin/sterling generate --spec openapi.yaml --config sterling.toml --enhance
        
    - name: Sync Documentation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./sync-vers-docs.sh
WORKFLOWEOF

echo "✅ Created GitHub Actions workflow"

# Create README for the setup
cat > STERLING_SETUP_README.md << 'READMEEOF'
# Sterling Automation Setup for hdresearch/chelsea

This setup enables automatic SDK generation and documentation updates when OpenAPI specifications change in the hdresearch/chelsea repository.

## Architecture

```
hdresearch/chelsea (OpenAPI changes)
        ↓ (webhook trigger)
Sterling SDK Generator
        ↓ (generates)
├── TypeScript SDK → hdresearch/chelsea-typescript-sdk
├── Rust SDK → hdresearch/chelsea-rust-sdk  
├── Python SDK → hdresearch/chelsea-python-sdk
├── Go SDK → hdresearch/chelsea-go-sdk
└── Documentation → hdresearch/vers-docs (PR)
```

## Setup Steps

1. **Configure Environment Variables**
   ```bash
   cp .env.example .env
   # Edit .env with your actual API keys and tokens
   ```

2. **Build Sterling**
   ```bash
   zig build -Doptimize=ReleaseFast
   ```

3. **Test Manual Generation**
   ```bash
   # Download Chelsea OpenAPI spec
   curl -o chelsea-openapi.yaml https://raw.githubusercontent.com/hdresearch/chelsea/main/openapi.yaml
   
   # Generate SDKs
   ./zig-out/bin/sterling generate --spec chelsea-openapi.yaml --config sterling.toml --enhance
   ```

4. **Set Up Webhook (for automation)**
   - Deploy webhook server to receive GitHub webhooks
   - Configure webhook in hdresearch/chelsea repository settings
   - Point to your Sterling webhook endpoint

## Manual Workflow

```bash
# 1. Generate SDKs from OpenAPI spec
./zig-out/bin/sterling generate --spec openapi.yaml --config sterling.toml --enhance

# 2. Sync documentation with vers-docs
./sync-vers-docs.sh
```

## Automated Workflow

When OpenAPI files change in hdresearch/chelsea:
1. GitHub webhook triggers Sterling
2. Sterling downloads the updated OpenAPI spec
3. Generates enhanced SDKs for all languages
4. Creates/updates SDK repositories
5. Generates documentation
6. Creates PR in hdresearch/vers-docs

## Configuration

The `sterling.toml` file configures:
- Source repository (hdresearch/chelsea)
- Target SDK repositories
- Documentation output (hdresearch/vers-docs)
- LLM enhancement settings
- GitHub automation settings

## Features

- **Multi-language SDK generation**: TypeScript, Rust, Python, Go
- **LLM enhancement**: AI-powered code improvement and documentation
- **GitHub automation**: Automatic repository creation and CI/CD setup
- **Documentation generation**: Mintlify-compatible docs for vers-docs
- **Package publishing**: Automatic publishing to npm, PyPI, crates.io
- **Webhook integration**: Automatic triggering on OpenAPI changes

## Monitoring

Check the following for automation status:
- GitHub Actions in this repository
- SDK repository commits and releases
- Pull requests in hdresearch/vers-docs
- Package registry publications
READMEEOF

echo ""
echo "🎉 Sterling automation setup complete!"
echo ""
echo "Next steps:"
echo "1. Edit .env with your actual API keys and tokens"
echo "2. Test manual SDK generation:"
echo "   curl -o test-openapi.yaml https://raw.githubusercontent.com/hdresearch/chelsea/main/openapi.yaml"
echo "   ./zig-out/bin/sterling generate --spec test-openapi.yaml --config sterling.toml --enhance"
echo "3. Set up webhook in hdresearch/chelsea repository"
echo "4. Deploy webhook server for automation"
echo ""
echo "📖 See STERLING_SETUP_README.md for detailed instructions"
