#!/bin/bash

# Script to sync generated documentation with hdresearch/vers-docs

set -e

echo "📚 Syncing documentation with hdresearch/vers-docs..."

# Check if docs were generated
if [ ! -d "./generated/docs" ]; then
    echo "❌ No generated docs found. Run Sterling generate first."
    exit 1
fi

# Clone or update vers-docs repository
if [ ! -d "./vers-docs" ]; then
    echo "📥 Cloning hdresearch/vers-docs..."
    git clone https://github.com/hdresearch/vers-docs.git
else
    echo "🔄 Updating vers-docs..."
    cd vers-docs
    git pull origin main
    cd ..
fi

# Copy generated docs to vers-docs
echo "📋 Copying generated documentation..."
mkdir -p vers-docs/docs/chelsea
cp -r generated/docs/* vers-docs/docs/chelsea/

# Create pull request (requires gh CLI)
cd vers-docs

if command -v gh &> /dev/null; then
    echo "🔀 Creating pull request..."
    
    # Create a new branch
    BRANCH_NAME="chelsea-docs-update-$(date +%Y%m%d-%H%M%S)"
    git checkout -b "$BRANCH_NAME"
    
    # Add and commit changes
    git add docs/chelsea/
    git commit -m "Update Chelsea API documentation

- Auto-generated from OpenAPI specification
- Updated SDK documentation for all languages
- Generated by Sterling SDK Generator"
    
    # Push and create PR
    git push origin "$BRANCH_NAME"
    gh pr create \
        --title "Update Chelsea API Documentation" \
        --body "Automated documentation update from Sterling SDK Generator.

This PR includes:
- Updated API reference documentation
- SDK installation and usage guides
- Code examples for all supported languages

Generated from the latest OpenAPI specification in hdresearch/chelsea." \
        --base main \
        --head "$BRANCH_NAME"
    
    echo "✅ Pull request created successfully"
else
    echo "⚠️  GitHub CLI not found. Please manually create a pull request with the changes."
    echo "   Branch: $BRANCH_NAME"
fi

cd ..
