#!/bin/bash
# Sync Chelsea OpenAPI spec to hdresearch/vers-docs
# Aligns with vers-docs Mintlify structure: api-reference/openapi.json
set -e

CHELSEA_SPEC="${1:-../chelsea/openapi/openapi.json}"
VERS_DOCS_DIR="${2:-./vers-docs}"

echo "📚 Syncing Chelsea OpenAPI to vers-docs..."

if [ ! -f "$CHELSEA_SPEC" ]; then
    echo "❌ Chelsea OpenAPI spec not found at $CHELSEA_SPEC"
    exit 1
fi

# Clone or update vers-docs
if [ ! -d "$VERS_DOCS_DIR" ]; then
    echo "📥 Cloning hdresearch/vers-docs..."
    git clone https://github.com/hdresearch/vers-docs.git "$VERS_DOCS_DIR"
else
    echo "🔄 Updating vers-docs..."
    cd "$VERS_DOCS_DIR" && git pull origin main && cd ..
fi

# Copy the OpenAPI spec (vers-docs uses api-reference/openapi.json natively)
echo "📋 Updating api-reference/openapi.json..."
cp "$CHELSEA_SPEC" "$VERS_DOCS_DIR/api-reference/openapi.json"

# Check for changes
cd "$VERS_DOCS_DIR"
if git diff --quiet api-reference/openapi.json; then
    echo "✅ No changes to sync"
    exit 0
fi

# Create PR
if command -v gh &> /dev/null; then
    BRANCH_NAME="chelsea-openapi-update-$(date +%Y%m%d-%H%M%S)"
    git checkout -b "$BRANCH_NAME"
    git add api-reference/openapi.json
    git commit -m "Update Chelsea API OpenAPI spec

Auto-synced from hdresearch/chelsea by Sterling SDK Generator."
    git push origin "$BRANCH_NAME"
    gh pr create \
        --title "Update Chelsea API Reference" \
        --body "Automated OpenAPI spec update from hdresearch/chelsea.

This PR updates the API reference documentation with the latest Chelsea OpenAPI specification.

Generated by [Sterling SDK Generator](https://github.com/hdresearch/sterling)." \
        --base main \
        --head "$BRANCH_NAME"
    echo "✅ Pull request created"
else
    echo "⚠️  gh CLI not found. Changes staged but PR not created."
    echo "   Run: cd $VERS_DOCS_DIR && git add -A && git commit && git push"
fi
cd ..
