FROM rust:1-alpine3.23

WORKDIR /usr/src/agent

RUN apk add alpine-sdk musl-dev openssl openssl-dev openssl-libs-static sqlite-static

COPY Cargo.lock .
COPY Cargo.toml .
COPY crates/agent_protocol crates/agent_protocol
COPY crates/chelsea-agent crates/chelsea-agent

RUN cargo build -r

