const std = @import("std");
const parser = @import("../parser/openapi.zig");
const config = @import("../config/config.zig");

pub const SDKGenerator = struct {
    allocator: std.mem.Allocator,
    spec: parser.OpenAPISpec,
    config: config.Config,

    pub fn init(allocator: std.mem.Allocator, spec: parser.OpenAPISpec, cfg: config.Config) SDKGenerator {
        return SDKGenerator{
            .allocator = allocator,
            .spec = spec,
            .config = cfg,
        };
    }

    pub fn generateAll(self: *SDKGenerator) !void {
        for (self.config.targets) |target| {
            try self.generateTarget(target);
        }
    }

    fn generateTarget(self: *SDKGenerator, target: config.Config.Target) !void {
        std.debug.print("Generating {s} SDK to {s}\n", .{ @tagName(target.language), target.output_dir });
        
        switch (target.language) {
            .typescript => try self.generateTypeScript(target),
            .rust => try self.generateRust(target),
            .python => try self.generatePython(target),
            .go => try self.generateGo(target),
        }
    }

    fn generateTypeScript(self: *SDKGenerator, target: config.Config.Target) !void {
        // Create output directory
        std.fs.cwd().makeDir(target.output_dir) catch |err| switch (err) {
            error.PathAlreadyExists => {},
            else => return err,
        };

        // Create client file path
        const file_path = try std.fmt.allocPrint(self.allocator, "{s}/client.ts", .{target.output_dir});
        defer self.allocator.free(file_path);

        const file = try std.fs.cwd().createFile(file_path, .{});
        defer file.close();

        const content = 
            \\// Generated by Sterling SDK Generator
            \\// OpenAPI Spec: {s} v{s}
            \\
            \\export class PetStoreClient {{
            \\  private baseUrl: string;
            \\  private apiKey?: string;
            \\
            \\  constructor(config: {{ baseUrl?: string; apiKey?: string }} = {{}}) {{
            \\    this.baseUrl = config.baseUrl || "https://api.petstore.com/v1";
            \\    this.apiKey = config.apiKey;
            \\  }}
            \\
            \\  async listPets(): Promise<Pet[]> {{
            \\    const response = await fetch(`${{this.baseUrl}}/pets`, {{
            \\      headers: {{
            \\        ...(this.apiKey && {{ "X-API-Key": this.apiKey }}),
            \\      }},
            \\    }});
            \\    return response.json();
            \\  }}
            \\}}
            \\
            \\export interface Pet {{
            \\  id: number;
            \\  name: string;
            \\  tag?: string;
            \\}}
            \\
        ;

        try file.writeAll(content);
        std.debug.print("Generated TypeScript client at {s}\n", .{file_path});
    }

    fn generateRust(self: *SDKGenerator, target: config.Config.Target) !void {
        _ = self;
        std.debug.print("Rust generation not implemented yet for {s}\n", .{target.output_dir});
    }

    fn generatePython(self: *SDKGenerator, target: config.Config.Target) !void {
        _ = self;
        std.debug.print("Python generation not implemented yet for {s}\n", .{target.output_dir});
    }

    fn generateGo(self: *SDKGenerator, target: config.Config.Target) !void {
        _ = self;
        std.debug.print("Go generation not implemented yet for {s}\n", .{target.output_dir});
    }
};
